// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5c13KEXBqAkOyA9GH52I7JnQVSmUe3BA',
    appId: '1:391501046086:web:673c240887df50fa54c547',
    messagingSenderId: '391501046086',
    projectId: 'copick-13aa2',
    authDomain: 'copick-13aa2.firebaseapp.com',
    storageBucket: 'copick-13aa2.appspot.com',
    measurementId: 'G-R4NVS6DZYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUWzKtsxRISH85B2_VKw7RYpAKD6gwLmE',
    appId: '1:391501046086:android:a824595e58fb615b54c547',
    messagingSenderId: '391501046086',
    projectId: 'copick-13aa2',
    storageBucket: 'copick-13aa2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjN0NGG4_dgHew6QriI3YZFALVk3aRBJI',
    appId: '1:391501046086:ios:2098099d1600d38654c547',
    messagingSenderId: '391501046086',
    projectId: 'copick-13aa2',
    storageBucket: 'copick-13aa2.appspot.com',
    iosBundleId: 'com.fouren.copickManageWithweb',
  );
}
